version: '3'
services:
  api:
    image: 631263/build_laravel_dev:1.1
    container_name: "build_laravel_dev.web"
    # build:
      # dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ".:/app"
    ports:
      - "8001:80"
    networks:
      - app
    depends_on:
      - mysql
      - redis
  mysql:
    container_name: "build_laravel_dev.db"
    image: 'mysql:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
    volumes:
      - './data.mysql:/var/lib/mysql'
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    networks:
      - app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
  redis:
    image: redis:6
    container_name: "build_laravel_dev.redis"
    volumes:
      - 'data.redis:/data'
    networks:
      - app
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
volumes:
  data.redis:
    driver: local
  data.mysql:
    driver: local
networks:
  app:
    driver: bridge